### ISSUE TITLE
IPs are not being created in NetBox

### ISSUE THREAD

**Issue by Lucaas333** [bbird81/Netbox-ipscanner#11]
I started using the script recently, however it is not feeding IPAM. It recognizes the IPs on the network, but does not create them within Netbox, can you help me?

**Comment by r-lindner** [comment]
Does the old script without my changes work?
https://raw.githubusercontent.com/bbird81/Netbox-ipscanner/0e52f86c5622d16ae893538e765402bb46c451f2/netbox_ipscanner.py

**Comment by bbird81** [comment]
> I started using the script recently, however it is not feeding IPAM. It recognizes the IPs on the network, but does not create them within Netbox, can you help me?

Any error messages? Explain what you are doing please.

**Comment by Lucaas333** [comment]
> > I started using the script recently, however it is not feeding IPAM. It recognizes the IPs on the network, but does not create them within Netbox, can you help me?
> 
> Any error messages? Explain what you are doing please.

Hello!

No, the script doesn't show me any error messages, it just doesn't create the IPs. I am attaching together an image of a scan that I performed on a prefix, it recognizes the IPs on the network, but does not feed the IPAM:

![image](https://github.com/bbird81/Netbox-ipscanner/assets/121646437/d7bc4518-005b-47a1-b64c-395dabe8b5c2)

I even tried to look for something on the internet regarding Pynetbox (I suspected that it could be the cause), but I was unsuccessful.

**Comment by Lucaas333** [comment]
> Does the old script without my changes work? https://raw.githubusercontent.com/bbird81/Netbox-ipscanner/0e52f86c5622d16ae893538e765402bb46c451f2/netbox_ipscanner.py

Hello friend

Using the code you passed, I got the following error message when using:

![image](https://github.com/bbird81/Netbox-ipscanner/assets/121646437/aa9a26f6-f5ee-40ae-9a80-f29dea953d6a)

Do you know what could be causing this? Recently to try to fix it, I updated to the latest available stable version of NetBox (3.6.0)

**Comment by bbird81** [comment]
I think you might have duplicate address entries in your IPAM, please check that.

**Comment by lasag-2511** [comment]
> I think you might have duplicate address entries in your IPAM, please check that.

I found one crazy issue today, though the ips are reachable (pingable) from netbox server, when i run script, it just updated the IP and status marked as "deprecated" and if i run again the script status marks as active . The status keeps on changing either to deprecated or active

In the log i see it as "Host 192.168.90.3/24 exists in netbox but not responding --> DEPRECATED" -- but this ip is reachable from netbox . Any suggestions why its not scanning properly..

**Comment by r-lindner** [comment]
maybe a rate limit on your network firewall that limits number of ping packets?

**Comment by lasag-2511** [comment]
> maybe a rate limit on your network firewall that limits number of ping packets?

Looks like we cannot scan multiple networks at a time, so Is it possible to set rate limit to scanner with in the script.

**Comment by Lucaas333** [comment]
> I think you might have duplicate address entries in your IPAM, please check that.

I exported all my addresses and left IPAM with no addresses and used the script. But he hasn't created the addresses yet. Am I having a problem with my Netbox?

**Comment by sag2643** [comment]
> > I think you might have duplicate address entries in your IPAM, please check that.
> 
> I found one crazy issue today, though the ips are reachable (pingable) from netbox server, when i run script, it just updated the IP and status marked as "deprecated" and if i run again the script status marks as active . The status keeps on changing either to deprecated or active
> 
> In the log i see it as "Host 192.168.90.3/24 exists in netbox but not responding --> DEPRECATED" -- but this ip is reachable from netbox . Any suggestions why its not scanning properly..

I also have the same issue, can anyone help

**Comment by sag2643** [comment]
> > > I started using the script recently, however it is not feeding IPAM. It recognizes the IPs on the network, but does not create them within Netbox, can you help me?
> > 
> > 
> > Any error messages? Explain what you are doing please.
> 
> Hello!
> 
> No, the script doesn't show me any error messages, it just doesn't create the IPs. I am attaching together an image of a scan that I performed on a prefix, it recognizes the IPs on the network, but does not feed the IPAM:
> 
> ![image](https://user-images.githubusercontent.com/121646437/265998706-d7bc4518-005b-47a1-b64c-395dabe8b5c2.png)
> 
> I even tried to look for something on the internet regarding Pynetbox (I suspected that it could be the cause), but I was unsuccessful.

I think the networkscan is broken

**Comment by Lucaas333** [comment]
I also think it's broken.
I need a script or plugin to keep the ip's updated, do you use one?

**Comment by bbird81** [comment]
It worked for sure 'till commit [0e52f86c5622d16ae893538e765402bb46c451f2](https://github.com/bbird81/Netbox-ipscanner/commit/c3c461b487a093a9f6840626d24f0368d394af16) with Netbox 3.5.

I don't have the opportunity to check more recent commits on Netbox 3.6, I'm sorry.

I think the script is very simple and debug it should be quite easy, feel free to mangle with it and eventually report what you found.

**Comment by lasag-2511** [comment]
@bbird81 : when i tried debug script, the network scan doesn't  scan the ips properly, it only identifies few ips and if others not found then it marks as deprecated. may be it works with other scanner tools ? for ex: nmap
@Lucaas333 : No i am trying to solve, but running out of ideas

**Comment by r-lindner** [comment]
I also exported+deleted all IP addresses and regenerated it. Some IPs were missing in the new list but these are all deprecated IPs - which were not marked as deprecated by the script. Maybe the part that marks IPs as deprecated is broken, I'll have a look.

[edit] My old list of IPs and the new list is matching if deprecated addresses are marked as "DEPRECATED". in #13 I fixed this. I cannot see a reason why IPs are not created.
The only reason I see is the increased scanning speed which might trip network firewalls.

**Comment by lasag-2511** [comment]
> I also exported+deleted all IP addresses and regenerated it. Some IPs were missing in the new list but these are all deprecated IPs - which were not marked as deprecated by the script. Maybe the part that marks IPs as deprecated is broken, I'll have a look.
> 
> [edit] My old list of IPs and the new list is matching if deprecated addresses are marked as "DEPRECATED". in #13 I fixed this. I cannot see a reason why IPs are not created. The only reason I see is the increased scanning speed which might trip network firewalls.

@r-lindner : I still have the issues with networkscan, when i run the script for once, it gives only some limited IPs, when i execute the script for second time it marks the previous Ips as deprecated, and i get all the new ips with active status, when i scan for the third time its same.
In the log i see it as "Host 192.168.90.3/24 exists in netbox but not responding --> DEPRECATED" and there is no rate limit set on firewall.

**Comment by lasag-2511** [comment]
> I also exported+deleted all IP addresses and regenerated it. Some IPs were missing in the new list but these are all deprecated IPs - which were not marked as deprecated by the script. Maybe the part that marks IPs as deprecated is broken, I'll have a look.
> 
> [edit] My old list of IPs and the new list is matching if deprecated addresses are marked as "DEPRECATED". in #13 I fixed this. I cannot see a reason why IPs are not created. The only reason I see is the increased scanning speed which might trip network firewalls.

My all IPs are marked as deprecated though its active. does netbox has a bug

**Comment by sag2643** [comment]
> I also exported+deleted all IP addresses and regenerated it. Some IPs were missing in the new list but these are all deprecated IPs - which were not marked as deprecated by the script. Maybe the part that marks IPs as deprecated is broken, I'll have a look.
> 
> [edit] My old list of IPs and the new list is matching if deprecated addresses are marked as "DEPRECATED". in #13 I fixed this. I cannot see a reason why IPs are not created. The only reason I see is the increased scanning speed which might trip network firewalls.

@r-lindner : does it work for you

**Comment by r-lindner** [comment]
yes, everything is working for me, that's what I tested in the previous comment.
